tarantool/test-run

lib/options.py
=> Set jobs using TEST_RUN_JOBS env variable

lib/options.py
=> Set tests list using TEST_RUN_TESTS env variable

lib/pytap13.py
Also added strict mode where we check each line of the output instead of
skipping, disabled for now.
=> pytap13: do not count subtests

lib/preprocessor.py, lib/tarantool_server.py, test_run.lua
=> Server start with extra args

lib/options.py, lib/test.py
Print subtest output to test-run log
See also: #76
=> Add option --verbose

lib/app_server.py
The code was copy-pasted from tarantool_server.py to app_server.py and
adopted a bit, but it would be better to generalize it and move to
test_suite.py. I understand this point, but don't want to be beaten by
corner cases during proper refactoring (at least within this commit).
=> Support configurations in core = 'app' tests

lib/server.py, lib/server_mixins.py, lib/test.py, lib/test_suite.py, lib/utils.py
=> Print whole reject file when test failed

dispatcher.py, lib/tarantool_connection.py, lib/utils.py
=> Don't inherit queues file descriptors

README.md, lib/app_server.py, lib/preprocessor.py, lib/server.py, lib/tarantool_server.py, lib/test.py, lib/test_suite.py, pre_cleanup.lua
By using param `pre_cleanup = True` test-run will copy
`pre_cleanup.lua` file then execute `clean()` from it before each
test in suite.
Part of https://github.com/tarantool/tarantool/issues/1961
=> Perform cleanup before each test if param used

lib/test.py
The bug was introduced in 5ecd4d797ec8bce5c3ad57659b2185e4210f44d7.
Fixes #130.
=> Fix *.reject file directory

lib/server.py, lib/tarantool_server.py, lib/test.py, lib/test_suite.py, pretest_clean.lua
No behaviour changes except the option name.
=> Rename pre_cleanup to pretest_clean

lib/preprocessor.py
Before this commit the following command fails when
use_unix_sockets_iproto is set to True:
test_run:cmd("set variable r_uri to 'replica.listen'")
The reason of the fail is that the following Lua statement is formed to
execute the command:
r_uri=/path/to/unix/socket
Found on replication/catch.test.lua from tarantool.
=> Fix test_run:cmd('set variable ...') for strings

README.md
=> readme: describe pretest_clean suite.ini option

README.md, lib/preprocessor.py, lib/tarantool_server.py, lib/utils.py
Added server kill routine based on server stop routine
except the SIGKILL is used instead of SIGTERM and server
is killing before connections stopping.
=> Add the signal option into stop server routine

test_run.lua
These functions are needed to wait for a certain state of an upstream /
downstream as tracked in box.info.replication.
Fixes #158.
=> Add wait_upstream() and wait_downstream()

dispatcher.py
=> Support more then 60 parallel jobs

pretest_clean.lua
See https://github.com/tarantool/tarantool/issues/4287 for example of a
problem it solves.
=> Collect garbage at pretest clean

lib/test.py
Before this commit it fails in the following way if there is no expected
result file (i.e. TAP13 result is expected):
| [001] Cannot find var/001_foo/bar.result
| [001]
| [001] Worker "001_foo" received the following error; stopping...
| [001] Traceback (most recent call last):
| [001]   File "/home/alex/<...>/test-run/lib/worker.py", line 294, in run_task
| [001]     task, self.server, self.inspector)
| [001]   File "/home/alex/<...>/test-run/lib/test_suite.py", line 210, in run_test
| [001]     short_status = test.run(server)
| [001]   File "/home/alex/<...>/test-run/lib/test.py", line 210, in run
| [001]     is_tap, is_ok = self.check_tap_output()
| [001] TypeError: 'bool' object is not iterable
| [001]
| [001] Exception: 'bool' object is not iterable
Or in the following way when there …
=> Fix reporting in case of lack of temporary result

lib/worker.py
Found that non restartable workers, used to run groups of tasks, had
only single tarantool server process started in the very start of it
at the worker's initalization. If any test in the worker's queue was
aborted then all the rest tests in queue couldn't be started. To fix
it the server restart commands were added just after the each task
failed. This change could decrease the performance, but it did not,
because in parallel runs these servers restarts don't use resources
and in absolute testing time was not increased. It happened because
there were other bottle necks in resources that made this change
invisible for the performance. Checking the change w/o parallel runs
found that even in this mode the running time wasn't increased too.
Closes #192
Closes #137
Closes #215
=> Restart server on each failed test in worker

.luacheckrc, .travis.yml, Makefile, test_run.lua
=> Fix warnings found by luacheck

lib/test.py, lib/test_suite.py, lib/worker.py, listeners.py, test-run.py
It looks like the 'checksum' machinery is dead, so let's remove it.
Closes #316
=> Drop 'checksum' machinery

lib/tarantool_server.py
This patch improves getting the iproto port for tarantool < 2.4.1. The previous revision of the lua script might give unstable result (more than 1 port) and test-run failed. Now it is fixed.
Follows up #141
=> Improve getting iproto port for tarantool < 2.4.1

listeners.py
=> Properly ignore Unix sockets on artifact saving

lib/luatest_server.py, lib/options.py
=> Allow to choose luatest cases to run

lib/tarantool_server.py, lib/utils.py
https://www.flake8rules.com/rules/E721.html
=> flake8: fix E721 do not compare types
