tarantool/test-run

- lib/tarantool_server.py
TarantoolStartError is subject to propagate to a joining greenlet,
consider `lib.inspector.gevent_propagate_exc()`.
> Handle non-default server crash

- lib/preprocessor.py
- test_run.lua
It is about 'create server' command and create_cluster() Lua function
from test_run.new() API.
The default behaviour was broken in da0fc359.
> Bring back default behaviour of test-run API

- lib/preprocessor.py
- lib/tarantool_server.py
- lib/worker.py
Usage:
```
test_run:cmd("start server <name> with crash_expected=True")
```
Also fixed non-default server crash reporting, regression after
9d73ef1281c59177c7c23aae1371e71b4038e7f1
Fixes #92.
> Support expected fail of non-default server

- lib/utils.py
Found empty lines in /proc/.../status on one Ubuntu 16.04 installation.
> Fix format_process function

- lib/app_server.py
- listeners.py
- test-run.py
- When test-run runs in a consistent mode, there is no reproduce information.
This mode is used in CI. It is convenient to see the contents of the reproduce
file in the CI log.
- If test fails in parallel mode, print the reproduce file content
- Fix some code health by using `flake8`
> Print reproduce file when test failed

- test_run.lua
Just like in case of `start server replica with args='1 2 3'`, it is
now possible to pass arguments to create_cluster, so that all instances
are started whith these arguments.
Also alter create_cluster a little bit: previous behaviour was to create
and start instances in a loop, change it to first creating all
instances and then starting them. This is needed because creating an
instance may take up a lot of time, if the old vardir isn't empty, and
the first started instance would have to wait for others for a
significant period of time, which makes it exit upon timeout if
replication_connect_timeout is relatively small.
Needed for tarantool/tarantool#3428
> Allow to pass arguments to create_cluster.

- lib/test_suite.py
- lib/worker.py
- listeners.py
- test-run.py
By default this param is True, if the test fails then the contents of
reproduce file are displayed. If the parameter is False, do not show
the contents of reproduce file.  For example, the 'sql-tap' tests run
each case in a separate tarantool instance, so reproduce is not
necessary for problem investigation. Used in 'suite.ini'.
Closes #113
> Add new config param 'show_reproduce_content'

- test_run.lua
Got this error then testing parallel mode.
Fixes: https://github.com/tarantool/tarantool/issues/3895
> fixed problem with lsn is not defined

- lib/preprocessor.py
- lib/tarantool_server.py
- lib/test_suite.py
The existing 'use_unix_sockets' option enables using of unix sockets for
admin (console) sockets. The new option enables it for iproto (binary
protocol) sockets.
The reason why it is done under a separate option is to shield existing
users from unexpected behaviour changes.
> Add 'use_unix_sockets_iproto' suite.ini option

- lib/__init__.py
src/fiber.h is moved to src/lib/core/fiber.h in 2.1.1-322-g3f5f59bb5,
see [1]. TARANTOOL_SRC_DIR is not set by test-run and
app-tap/http_client.test.lua fails with the following error in logs:
sh: 1: ../../test/app-tap/httpd.py: not found
[1]: https://github.com/tarantool/tarantool/commit/3f5f59bb53908d432659408c746f54cfbf67411e
> Fix TARANTOOL_SRC_DIR with recent tarantool

- lib/unittest_server.py
It seems natural to set cwd to a var directory for a unit test to, say,
allow it to produce log files that will be under a gitignored directory.
We already run servers for other test suite types (tarantool and app) in
a var directory.
> Run a unit test from a var directory

- pretest_clean.lua
Before this commit, if there are a registered function, clean() function
fails when pretest_clean option is enabled in suite.ini.
> Fix _func system space clean

- lib/admin_connection.py
- lib/preprocessor.py
- lib/pytap13.py
- lib/tarantool_server.py
- lib/worker.py
- requirements.txt
GitHub warns about pyyaml < 4.2b1, because of CVE-2017-18342:
yaml.load() could cause arbitrary code execution. I think it is not very
important in the case of test-run, because a test code is controlled by
a user, but anyway it is good to be up to date.
Eliminated new pyyaml warnings about using of unsafe yaml.load():
replaced it with yaml.safe_load(). We don't construct Python classes
directly according to yaml tags, so safe_load() fit our needs.
> Update pyyaml version

- lib/test_suite.py
A worker can be interrupted with SIGINT (by Ctrl+C) at the moment when a
server (TarantoolServer, AppServer or UnittestServer) is not created. In
this case test-run shows the following exception:
| Process Process-21:
| Traceback (most recent call last):
|   File "/usr/lib64/python2.7/multiprocessing/process.py", line 267, in _bootstrap
|     self.run()
|   File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
|     self._target(*self._args, **self._kwargs)
|   File "/home/alex/projects/tarantool-meta/tarantool/test-run/dispatcher.py", line 378, in _run_worker
|     worker = self.gen_worker(worker_id)
|   File "/home/alex/projects/tarantool-meta/tarantool/test-run/lib/worker.py", line 243, in __init__
|     self.stop_server(cleanup=False)
|   File …
> Better handle keyboard interrupt

- dispatcher.py
- test-run.py
This commit handles the case when test-run found that some of scheduled
tasks were not reported as finished by workers. The old behaviour leads
to zero exit code in the case when --force option is not set (looks as
the unintended mistake).
Now this situation causes a testing fail (non-zero exit code) and it
does not matter whether --force option is set.
Show list of failed tasks always except the case when it is caused by a
keyboard interruption.
While we are here clarified and changed related test-run messages.
All that is about the situation that should never occur. See #115 for
such cases.
> Fail testing when test-run fails internally

- lib/app_server.py
When test_run:cmd('start server foo') is called from an app test and
tarantool fails to start, the following exception is shown:
| [010] Worker "010_app-tap" received the following error; stopping...
| [010] Traceback (most recent call last):
| [010]   File "/home/alex/projects/tarantool-meta/tarantool/test-run/lib/worker.py", line 294, in run_task
| [010]     task, self.server, self.inspector)
| [010]   File "/home/alex/projects/tarantool-meta/tarantool/test-run/lib/test_suite.py", line 208, in run_test
| [010]     short_status = test.run(server)
| [010]   File "/home/alex/projects/tarantool-meta/tarantool/test-run/lib/test.py", line 180, in run
| [010]     self.execute(server)
| [010]   File "/home/alex/projects/tarantool-meta/tarantool/test-run/lib/app_server.py", line 43, in execute
| …
> Catch non-default server start fail in app server

- lib/tarantool_server.py
We should not try to kill non-default servers that was not started yet.
Before this commit the following exception can occur.
| [001] Test.run() received the following error:
| [001] Traceback (most recent call last):
| [001]   File "/home/alex/projects/tarantool-meta/tarantool/test-run/lib/test.py", line 180, in run
| [001]     self.execute(server)
| [001]   File "/home/alex/projects/tarantool-meta/tarantool/test-run/lib/tarantool_server.py", line 154, in execute
| [001]     self.killall_servers(server, ts, crash_occured)
| [001]   File "/home/alex/projects/tarantool-meta/tarantool/test-run/lib/tarantool_server.py", line 108, in killall_servers
| [001]     bad_returncode = server.process.returncode not in (None,
| [001] AttributeError: 'TarantoolServer' object has no attribute 'process'
> Fix killing of servers at crash

- lib/tarantool_server.py
Show logs and only then reraise TarantoolStartError (see
TarantoolServer.start()).
Don't show logs on an instance that acquires to start an instance, e.g.
default one (see LuaTest.execute()).
How to reproduce using tarantool test suite:
| diff --git a/test/box/proxy.lua b/test/box/proxy.lua
| index fa87ab879..a90f24715 100644
| --- a/test/box/proxy.lua
| +++ b/test/box/proxy.lua
| @@ -2,7 +2,7 @@
|  os = require('os')
|  box.cfg{
| -    listen              = os.getenv("LISTEN"),
| +    listen              = 3301,
|      memtx_memory        = 107374182,
|      pid_file            = "tarantool.pid",
|      rows_per_wal        = 50
Hold 3301 port. Say, using tarantool:
| ./src/tarantool <<< 'box.cfg{listen = 3301}' &
Run a test that performs default server restarting:
| cd test && …
> Show logs for a non-default server failed at start

- lib/utils.py
open() in print_unidiff() fails before this commit, because TAP13 tests
have no result file.
Fixes #155.
> Fix TAP13 hung test reporting

- test-run.py
Tests are dispatched to task queue dispatchers at start and so it is
normal that tests can be not consumed when a test fails in non-force
mode or when a test hung. It is not test-run error.
The problem part with a failed (not hung) test was introduced in
d8abc031a6de3603b94660d66872f0485b5910cc ('Fail testing when test-run
fails internally').
Reported in
https://github.com/tarantool/test-run/issues/159#issuecomment-488065589
> Fix false positive internal error detection

- pretest_clean.lua
We'll add decimal built-in module in the scope of
https://github.com/tarantool/tarantool/issues/692
> pretest_clean: add decimal to standard packages

- README.md
- lib/tarantool_server.py
- lib/test_suite.py
- lib/utils.py
- listeners.py
Actually three features are introduced with this commit.
Now test-run recognizes *.test.sql files.
The content of those files are SQL statements written line-by-line. A
long statement may be splitted, see the next section.
The implementation leans on '\set language [lua|sql]' command of
tarantool console: appropriate language is set depending of a file name:
*.test.lua or *.test.sql before executing commands for a test file.
A value of 'engine' option when it is provided by a configuration has a
special meaning for *.test.sql tests (a configuration is a file set by
'config' option in suite.ini) . If it is 'memtx' or 'vinyl', then
corresponding default engine will be set for SQL subsystem before
executing commands for a test file. The implementation uses "pragma …
> Implement SQL driver

- pretest_clean.lua
app/strict.test.lua expects that 'a' variable is not declared at the
start of the test. However if the strict mode is enabled (which is
default in a debug build) global variables assignments are tracked
inside a metatable of _G. A variable is considered declared even if it
is set to `nil`.
If a test that runs before app/strict.test.lua set 'a' to any value,
then app/strict.test.lua will fail.
So we need to clean the metatable of _G in addition to _G itself.
> pretest_clean: clean strict module state

- lib/admin_connection.py
pyyaml is unable to parse complex dictionary keys: say, a list or a
dictionary. See https://github.com/yaml/pyyaml/issues/88
Tarantool however supports this kind of output:
```
tarantool> {[{k = 'v'}] = 1}
---
- ? k: v
: 1
...
```
When such response is arrived to test-run, pyyaml raises 'found
unhashable key' exception and test-run reports it as '[Lost current
connection]'.
Let's consider 'core = tarantool' tests. There is no much need to verify
whether a tarantool answer is well-formed yaml document, because it
anyway will be verified against a result file. And also it is unable to
handle the case above. So the check is removed.
See https://github.com/tarantool/tarantool/issues/4421
> Don't check whether yaml responses are well-formed

- dispatcher.py
- lib/test_suite.py
- lib/worker.py
Added "fragile" option with a list of tests that are not intended to be run in parallel with others. The format of the list is the same as for "disabled" option.
> Postpone fragile tests

- lib/app_server.py
- lib/options.py
- lib/server.py
- lib/tarantool_server.py
- lib/unittest_server.py
The option allows to avoid execution of a certain subset of tests.
The option sets a pattern for exclusion and all tests are filtered using
it: if a full test name (say, app-tap/string.test.lua) contains the
pattern as a substring, then the test will be excluded from execution.
The option can be passed several times to set several exclusions
patterns.
A list of such exclusion patterns also can be provided using
TEST_RUN_EXCLUDE environment variable (patterns are separated by
whitespaces).
If both the environment variable and the option are provided, then the
environment variable value will be ignored.
Trick: `--exclude foo/` allows to exclude a test suite.
Fixes #54.
> Add --exclude option

- lib/inspector.py
- test_run.lua
When test-run's inspector listens on a IPv4 port and some other process
listens on a IPv6 port of the same number, test_run:cmd() could connect
to this process rather then the inspector, because 'localhost' hostname
was used to connect.
Now test-run passes actual IP address of the inspector via an
environment variable and test_run:cmd() uses it to avoid the ambiguity
that is described above.
The problem was found during many parallel runs of app/socket.test.lua
test from tarantool, see case 4 in [1] (untitled, see right under case
3). This test starts many TCP servers and in rare cases a server port
may be the same as inspector's one.
There are two details that increase probability of the problem:
* It seems test-run's inspector always listens on IPv4 address, because
it is configured …
> Use exact IPv4/IPv6 address in test_run:cmd()

- pretest_clean.lua
We're going to implement it in the scope of
https://github.com/tarantool/tarantool/issues/4031
> pretest_clean: add popen built-in module

- lib/app_server.py
Update 'use_unix_sockets_iproto' for 'core = app'
Updated 'use_unix_sockets_iproto' option to support 'core = app'
tests, which enabled unix sockets for iproto connections. It helped
to handle the problem with 'Address already in use' error.
Part of issue https://github.com/tarantool/tarantool/issues/4459
> Update 'use_unix_sockets_iproto' option for core = app tests

- lib/app_server.py
'core = app' test (as well as 'core = tarantool' one) may start more
servers within a test using the following commands:
```lua
local test_run = require('test_run').new()
test_run:cmd("create server foo with script='foo.lua'")
test_run:cmd("start server foo")
```
AppServer sets LISTEN environment variable for its child processes. New
servers, which are started from a test, do the same within the same 
test-run worker process (at 'create server <...>' command) and so they
rewrote the environment variable.
Usually everything works even despite unexpexted iproto socket name, but
let's consider the following case:
```lua
-- test1.test.lua
box.cfg({listen = os.getenv('LISTEN')})
-- test1 listening now on app_server.socket-iproto
test_run:cmd("create server foo with script='foo.lua'")
-- foo …
```
> Fix 'use_unix_sockets_iproto' for 'core = app'

- dispatcher.py
- listeners.py
- test-run.py
ArtifactsWatcher listener collects list of all workers with failed
tests. After overall testing finishes it copies workers artifacts
files from its running 'vardir' sub-directories to the common path
'<vardir>/artifacts' to be able to collect these artifacts later.
Closes #90
> Collect results artifacts of the failed workers

- dispatcher.py
- lib/worker.py
- listeners.py
Set flow style (JSON-like) explicitly instead of block style to don't
break indentation.
Before the patch (incorrect):
```yaml
- - app-tap/iconv.test.lua
- null
```
After the patch:
```yaml
- [app-tap/iconv.test.lua, null]
```
The default was changed in [1].
[1]: https://github.com/yaml/pyyaml/pull/256
> Fix reproduce file formatting (use flow style)

- lib/test.py
- lib/test_suite.py
- lib/worker.py
- listeners.py
Added ability to use fragile list in JSON format from 'suite.ini'
files.
```
fragile = {
"retries": 10,
"tests": {
"bitset.test.lua": {
"issues": [ "gh-4095" ],
"checksums": [ "050af3a99561a724013995668a4bc71c", "f34be60193cfe9221d3fe50df657e9d3" ]
}
}}
```
Added ability to set per suite in suite.ini configuration file
'retries' option, which sets the number of accepted reruns of
the tests failed from 'fragile' list.
Added ability to check failed tests w/ fragile list to be sure that
the current fail equal to the issue mentioned in the fragile list.
Closes #189.
> Enable test reruns on failed fragiled tests

- test_run.lua
Wait until box will be initialized and an instance with given ID will
appear in the box.info.replication table.
The following testing problems should be fixed by this change:
https://github.com/tarantool/tarantool/issues/5317
https://github.com/tarantool/tarantool/issues/5329
Fixes #221
> wait_upstream / wait_downstream: wait box.cfg()

- README.md
- lib/test.py
Changed the path for saving *.reject files, for now it is saving in
the `<vardir>/<suite>` subfolder given in options or set localy as
`var/<suite>` by default.
> prepare test-run for out of source build

- lib/colorer.py
- lib/inspector.py
- lib/options.py
- lib/preprocessor.py
- lib/tarantool_server.py
- lib/worker.py
- listeners.py
- test_run.lua
Sometimes it is hard to understand what exactly the testing system doing. In this patchset I made attempt to improve its observability: give meaningful error messages, log more events and so on.
I picked up [one of the tests][1], which fails from time to time, and use it as a test for the testing system: run it, look at output and logs, change test-run to give me useful details, repeat.
[1]: https://github.com/tarantool/tarantool/issues/5395
> Improve observability of the testing system

- lib/utils.py
- listeners.py
When there is no output from workers during a long time (10 seconds by
default or 60 seconds when --long argument is passed), test-run prints a
warning and shows amount of lines in the temporary result file. It is
useful to understand on which statement a test hungs.
I reproduced the problem, when mangled tarantool to ignore SIGTERM and 
SIGINT signals and run a simple 'tarantool = core' test. The test
successfully passes, but the worker stucks in waiting for stopping the 
tarantool server.
This particular case should be resolved in PR #186, but just because the 
timeout for stopping the server is less than the warning delay. This
assumption looks fragile, especially if we'll want to make some of those
timeouts / delays configurable. Let's handle the situation when the file
does not …
> Handle lack of a last result file at a worker hang

- .tarantoolctl
- lib/__init__.py
- lib/options.py
- lib/tarantool_server.py
1. Move tarantoolctl to test-run tool submodule
Moved tarantoolctl to test-run tool submodule repository as:
<tarantool repository>/test-run/.tarantoolctl
Also set backward compability to use old path location:
<tarantool repository>/test/.tarantoolctl
as its primary place.
To set PWD environment for tarantoolctl for popen() call tried to use
os.environ. It was needed for the later commits where tarantoolctl
would be moved from to test-run repository and its configuration file
would be read right from the working directory of the test. In this
case all os.putenv() calls changed to environment set with os.environ,
to be able to modify environment directly, check [1] ("Note: Calling
putenv() directly does not change os.environ"). But in this case all
the tests had to be changed to use …
> Move tarantoolctl to test-run tool submodule and add replication_sync_timeout to it

- lib/app_server.py
- lib/options.py
- lib/tarantool_server.py
Added 'test-timeout' option to be able to break the test process with
kill signal if the test runs longer than this amount of seconds. By
default it is equal to 110 seconds. This value should be bigger than
'replication-sync-timeout' (which is 100 seconds by default) and
lower than 'no-output-timeout' (which is 120 seconds by default).
This timeout helped to avoid of issues with hanging tests till reach
of 'no-output-timeout' timeout, when overall testing exits. For now
if the test hangs than 'test-timeout' timeout helps to exit the test
processes. It gives the test-run worker chance to restart the failed
test either continue tests in worker queue. Before this fix tests,
hanged, like [1] and [2], for now the same issues resolved, like [3]
and [4] appropriate.
To reproduce the issues like …
> Add test_timeout to limit test run time

- lib/app_server.py
- lib/preprocessor.py
- lib/tarantool_server.py
Attempt to get rid of 'The daemon is already running' error and hang instances after testing.
- Wait for a process to terminate after a signal to get rid of the 'The daemon is already running' error.
- Stop supplementary (non-default) instances after an app test.
- Use SIGKILL, when SIGTERM is not sufficient for non-default instance of an app test (follows up #186).
- Kill an app server if it hangs and a non-default instance fails.
I use the test cases from the PR #244 and tweak them to hang or fail instances at different points: before startup or after. Say, hang a default app server and fail a supplementary one after startup.
Follows up PR #244.
Fixes #65.
Fixes #157.
----
While looking into this, found several doubtful situations or code: #252, #253, #254, #255, #256.
> Stop instances properly

- dispatcher.py
- lib/options.py
- test-run.py
Added ability to set using environment the following timeouts based on
appropriate run options:
```
TEST_TIMEOUT			--test-timeout
NO_OUTPUT_TIMEOUT		--no-output-timeout
REPLICATION_SYNC_TIMEOUT	--replication-sync-timeout
```
Closes #258
> Add timeouts setup from environment

- dispatcher.py
Found issue:
```
No output during 10 seconds. Will abort after 120 seconds without output. List of workers not reporting the status:
- 001_sql-tap [sql-tap/index4.test.lua, vinyl] at var_hdd_test/001_sql-tap/index4.result:0
[001] sql-tap/index4.test.lua                         vinyl           Test timeout of 110 secs reached  [ fail ]
[001] Test failed! Output from reject file var_hdd_test/rejects/sql-tap/index4.reject:
[001]
[001] Last 15 lines of Tarantool Log file [Instance "app_server"][/source/test/var_hdd_test/001_sql-tap/index4.test.lua:vinyl.tarantool.log]:
[Main process] Got failed test; gently terminate all workers...
Traceback (most recent call last):
File "./test-run.py", line 230, in <module>
status = main_parallel()
File "./test-run.py", line 145, in main_parallel
res = …
```
> OSError on process.terminate on hard loaded hosts

- test_run.lua
Found issue in testing:
```    
[006] --- replication/election_qsync.result   Fri Oct 16 00:12:02 2020
[006] +++ replication/election_qsync.reject   Sat Oct 17 19:08:11 2020
[006] @@ -89,6 +89,8 @@
[006]  -- Wait replication to the other instance.
[006]  test_run:wait_lsn('default', 'replica')
[006]   | ---
[006] + | - error: '...sitories/tarantool/test/var/006_replication/test_run.lua:68: attempt
[006] + |     to compare nil with number'
[006]   | ...
```    
Found that wait_lsn() routine from test_run.lua script failed on
comparing returned result from get_lsn() routine with real integer.
It happened because get_lsn() returned 'nil' on the freshly
bootstrapped instance. It happened when replica vclock [1:x, 2:1],
while master vclock [1:x, 2:0], but in box.info.vclock[2] is nil
instead …
> Add check in wait_lsn for nil value

- lib/tarantool_server.py
How to spot the problem visually:
```
[Main process] No output from workers. It seems that we hang. Send
SIGKILL to workers; exiting...
```
How to reproduce:
```
(Patch Python to trigger GC inside Colorer._write().)
$ diff -u /usr/lib/python3.9/multiprocessing/connection.py{.orig,}
--- /usr/lib/python3.9/multiprocessing/connection.py.orig
+++ /usr/lib/python3.9/multiprocessing/connection.py
@@ -202,6 +202,8 @@
raise ValueError("size is negative")
elif offset + size > n:
raise ValueError("buffer length < offset + size")
+        import gc
+        gc.collect()
self._send_bytes(m[offset:offset + size])
def send(self, obj):
(Just in case, my tarantool version.)
$ ./src/tarantool --version | head -n 1
Tarantool 2.8.0-134-g81c663335
(Add the reduced test case.)
$ cat …
```
> Fix hang on GC in Colorer._write()

- lib/__init__.py
- lib/options.py
The ability to select an allocator for memtx has been added to
tarantool. To test a new type of allocator, all tests must also
be run with it. Implemented new option, which allows to set allocator
for memtx. If you wan't to choose allocator type for tests, run test-run.py
with --memtx-allocator="small" or --memtx-allocator="system". Allocator type
is passed via MEMTX_ALLOCATOR environment variable to the test.
Part of https://github.com/tarantool/tarantool/issues/5419
> Implement new option, which allows to set allocator for memtx

- .github/workflows/test.yml
- .luacheckrc
- Makefile
- test/test-app/cfg.test.lua
- test/test-app/suite.ini
- test/test-run.py
- test/test-tarantool/box.lua
- test/test-tarantool/engine.cfg
- test/test-tarantool/iproto.result
- test/test-tarantool/iproto.test.py
- test/test-tarantool/replica.lua
- test/test-tarantool/set_language.result
- test/test-tarantool/set_language.test.sql
- test/test-tarantool/setopt_delimeter.result
- test/test-tarantool/setopt_delimeter.test.lua
- test/test-tarantool/suite.ini
- test/test-tarantool/worker_hang_when_gc_triggered_inside_colorer.result
- test/test-tarantool/worker_hang_when_gc_triggered_inside_colorer.test.lua
- test/test-unit/broken_unicode.result
- test/test-unit/broken_unicode.test
- test/test-unit/suite.ini
test-run supports three types of tests:
- tarantool - Test-Suite for Functional Testing
- app - Another functional Test-Suite
- unittest - Unit-Testing Test Suite
Patch adds tests for two of supported test types:
- test-app
- test-tarantool
How-to run:
$ mkdir build && cd build
$ make test_integration
> test: add initial test suite

- lib/colorer.py
- lib/options.py
- lib/singleton.py
Don't parse command line arguments each time `Options()` is called.
The metaclass syntax was changed in Python 3 (see [1]) and it is tricky
to add a metaclass in a Python version agnostic way. Still possible, but 
the code would be hard to understand. So I get rid of the Singleton
metaclass and use \_\_new\_\_() to implement this logic.
Aside of the Option class, we had another singleton: Colorer. However it
is instanciated once (this instance is exposed as color_stdout) and it
does not matter, whether it is a singleton or not.
A brief testing on tarantool's test suite (with --long --force) gives me
~8 minutes after the fix instead of ~11 minutes before the fix. However
it worth to note that we have a lot of tests, which are marked as
fragile and so run without parallelization. Otherwise …
> Fix slowdown on Python 3

- lib/server_mixins.py
- requirements.txt
- Drop six, argparse, msgpack-python.
- Relax PyYAML and gevent version requirements (freeze only major version).
Supersedes PR #282.
> Renew dependencies

- lib/worker.py
Previously, if reproduce file contained both fragile and stable tests
test run would failed. To avoid this case fragile tests now are using
as a stable.
Fixes: #233
> Fix --reproduce mode for fragile tests

- lib/__init__.py
- lib/app_server.py
- lib/server.py
- lib/tarantool_server.py
- lib/unittest_server.py
Previously if suite.ini has a release_disabled field it works only for
tarantool tests. This commit allows to use it for app- and unittests
suites.
Despite unittest does not take tarantool binary, unittests get version
(release/debug) from the tarantool binary information.
For instance,
Add line to test-unit/suite.ini:
`release_disabled = broken_unicode.test`
On debug version:
`[001] test-unit/broken_unicode.test                                   [ pass ]`
On release version:
`[001] test-unit/broken_unicode.test                                   [ disabled ]`
Closes: #199
> Add release_disabled field to app- and unit- tests

- lib/tarantool_server.py
Was fixed check that the answer is equal to `'loading'`. There was a
wrong condition and any substring of `'loading'` seemed like a correct
and equal to it.
One element tuple in python is defined as `(element,)`, without
a comma is a string.
Closes: #301
> Fix wrong condition in wait_until_started

- dispatcher.py
- lib/app_server.py
- lib/sampler.py
- lib/tarantool_server.py
- lib/test_suite.py
- lib/unittest_server.py
- lib/utils.py
- lib/worker.py
- listeners.py
Patch set consists of 3 commits:
1. sampler: add simple sampling infrastructure
Track tarantool and unit test executables that are run using test-run
with metainformation: worker, test, test configuration and server name.
Add a function that will be called each 0.1 second for each tracked
process.
The implementation tracks non-default servers and re-register default
servers that executes several tests ('core = tarantool' case).
Part of #277
2. Add RSS statistics collecting.
Found that some tests may fail due to lack of memory. Mostly it happens
in CI on remote hosts. To be able to collect memory used statistic
decided to add RSS memory status collecting routine get_proc_stat_rss()
which parses files:
```
/proc/<worker pid>/status
```
for RSS value 'VmRSS' which is size of memory portions. …
> Add RSS statistics and timings collecting

- pretest_clean.lua
This patch adds the built-in SQL function UUID() to the list of allowed
functions. This function is described in RFC "Consistent Lua/SQL types"
and will be added as part of issue tarantool/tarantool#5886.
Needed for tarantool/tarantool#5886.
> pretest_clean: add SQL built-in function UUID()

- lib/test.py
If a temporary test result file contains a non-unicode symbol, it will raise
additional logging and will fail the test.
Closes: #293
> Add error log for files with non-unicode symbol 

- test_run.lua
Also re-raise an error in test_run:eval() for better error reporting.
See the linked issue and commit messages for details.
Fixes https://github.com/tarantool/tarantool-qa/issues/128.
> Retry on a Lua error in test_run:wait_cond()

- lib/app_server.py
- lib/tarantool_server.py
- listeners.py
See https://github.com/tarantool/tarantool/pull/6365 for details about
possible problems and the description how it occurs.
We're going to use tags like 2.10.0-beta1 and so the build directory
path under rpmbuild will be even longer than before. So we should
decrease the absolute path length of a unix socket and so it worth to
trim the basename.
Of course, sooner or later we should elaborate a full solution.
> Decrease unix socket filename length

- test-run.py
The problem is that the test-run.py script returns exit code 0 in case of using
'-j -1' option even though some tests were failed during test run. This patch
fixes this false positive behavior by checking test status in a proper way.
> Fix false positive behavior of test-run.py in case of using '-j -1' opt

- README.md
- lib/options.py
- lib/server.py
- lib/tarantool_server.py
- lib/test_suite.py
- lib/utils.py
- test-run.py
Usage:
```sh
./test-run.py --tags foo
./test-run.py --tags foo,bar app/ app-tap/
```
test-run will run only those tests, which have at least one of the
provided tags.
Show a list of tags:
```sh
./test-run.py --tags
./test-run.py app-tap/ --tags
```
The tags metainfo should be placed within a first comment of a test
file.
Examples:
* .lua file:
```lua
#!/usr/bin/tarantool
-- tags: foo, bar
-- tags: one, more
<...>
```
* .sql file:
```sql
-- tags: foo
-- tags: bar
<...>
```
* .py file:
```python
<...>
```
Unsupported features:
* Marking unit tests with tags.
* Multiline comments (use singleline ones for now).
Fixes #22
> Support tags

- lib/worker.py
This will speed up tarantool/tarantool testing about 3 times.
> Enable parallel invocation of fragile tests

- lib/luatest_server.py
This patch adds writing the `reject` file contents of failed luatest
tests to the console output like it is done for TAP tests. This is
needed because it contains full information about failed tests.
Before:
```bash
======================================================================================
WORKR TEST                                            PARAMS          RESULT
---------------------------------------------------------------------------------
[001] vinyl-luatest/update_optimize_test.lua
[001] not ok 1 vinyl-luatest.update_optimize.test_optimize_one_index #
[001] not ok 3 vinyl-luatest.update_optimize.test_optimize_UPDATE_with_field_num_more_than_64 #
[001] not ok 4 vinyl-luatest.update_optimize.test_optimize_update_does_not_skip_entire_key_during_dump #
[001] Rejected …
```
> Improve report for failed luatest tests

- .luacheckrc
- Makefile
- lib/options.py
- lib/tarantool_server.py
- test-run.py
- test/unittest/box-cc0544b6afd1.lua
- test/unittest/hang.test.lua
- test/unittest/replica-7f4d4895ff58.lua
- test/unittest/suite.ini
- test/unittest/test_tarantool_server.py
This patch includes 4 commits:
**Use gevent sleep for switching context**
`time.sleep` was changed to `gevent.sleep` to allow current greenlet to
sleep and others to run. When `time.sleep` is used, greenlet's context
is not changed from the main process to test's greenlet.
As a result of this, there is no data received by the main process while
hanging the tarantool server process and the test is fallen down by the
common timeout (NO_OUTPUT_TIMEOUT). Even worse, the tarantool server
process is not killed by test-run.
Using `gevent.sleep` makes the test fail by the test timeout and kill
the farantool server process.
Part of #276
**Add timeout for starting tarantool server**
When a tarantool server starts, it waits for a special pattern in the
log file to proceed. If there is no pattern …
> Add timeout for starting tarantool server

- lib/test_suite.py
- lib/worker.py
test-run supports functionality to rerun failed tests in place, but
these tests have to be on so called fragile list. To add a test to the
fragile list we need to add a special configuration to the suite.ini
file of a test suite. Configuration example:
fragile = {
"retries": 5,
"tests": {
"tarantoolctl.test.lua": {
"issues": [ "gh-5059", "gh-5346" ]
},
"debug.test.lua": {
"issues": [ "gh-5346" ]
},
...
}
}
Rerunning failed tests in place is quite convenient because it allows us
to avoid rerunning all tests again and thus save time.
But to make it work as expected we should keep the list of fragile tests
always up-to-date. Flaky tests may be introduced every day and keeping
the list of fragile tests always up-to-date becomes extremely difficult
to do.
So our solusion is quite simple: just …
> Rerun all failed tests, not only marked as fragile

- lib/tarantool_server.py
This change reverts the previous fix (because it was wrong) and 
provides the proper solution of the issue. 
It was found that hanging processes of not started tarantool servers
are not killed by test-run and leave to hang. This situation can be
reproduced by creating the main server, then creating a replica server,
but the replica server is unable to join the master, for example, due
to lack of user permissions. In this case, the test fails by the server
start timeout and test-run kills the main server process only.
This patch fixes the issue.
Fixes #256
Follows #276
> Kill hanging processes of not started servers (reworked fix)

- lib/options.py
- lib/test_suite.py
This change adds the --retries (-r) option for having a facility to tune
the number of test run retries after a failure. Besides regular tests,
it is also the default value for 'fragile' tests unless the `retries`
option is set in the suite.ini config file.
Also, it introduces the `TEST_RUN_RETRIES` env variable to tune retries
count via shell (useful for CI systems).
Closes #334
> Add option to tune test run retries after failure

- README.md
- lib/__init__.py
- lib/luatest_server.py
- lib/options.py
- lib/server_mixins.py
- lib/tarantool_server.py
- lib/utils.py
- test-run.py
Usage:
```shell
$ . <(./test/test-run.py --env)
```
(Or copy-paste `./test/test-run.py --env` output into a shell.)
test-run ships luatest sources, but it is tricky to use it directly, because it requires to set appropriate `LUA_PATH`.
The new option prints all environment variables, which test-run sets at initialization, including `PATH` and `LUA_PATH`. The variables are printed in the format suitable for sourcing into a shell.
So now it is easy to call something like `luatest -v -p test_case_name`.
Fixes #325.
> Add an option to show test-run's environment variables

- lib/options.py
Now the default value for the `vardir` option is `/tmp/t`. This change
should help to solve the issue with the max length of the socket paths
(107 chars) in most cases.
Also, the default value for the `vardir` option is taken from the `VARDIR`
env variable when it is defined.
> Change default value for vardir option 

- lib/tarantool_server.py
- lib/worker.py
When a tarantool server failed to start when running *.test.py tests,
the corresponding test was not considered by test-run as a failed test.
As a result of that, log artifacts were not gathered by test-run. Now
it is fixed.
Fixes #333
> Fail *.test.py tests in case of srv start errors

- .github/workflows/test.yml
- lib/colorer.py
- listeners.py
See https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/ for details.
> Report job summary on GitHub Actions

- dispatcher.py
- lib/app_server.py
- lib/box_connection.py
- lib/inspector.py
- lib/preprocessor.py
- lib/tarantool_server.py
- lib/test_suite.py
- lib/utils.py
- test/test-app/suite.ini
- test/test-tarantool/suite.ini
- test/unittest/suite.ini
- test/unittest/test_lib_utils.py
This change replaces manual choosing an iproto port for TarantoolServer
by the auto resolving mechanism. In two words, test-run always provides
'127.0.0.1:0' as a value for LISTEN env variable that is used in a lua
file to start a tarantool instance. In this way, the port will be picked
automatically, and we are getting the real value of it via the admin
console by executing `box.info.listen` that is available for tarantool
version >= 2.4.1, and special lua script intended for tarantool version
< 2.4.1.
The same for AppServer, test-run always provides '127.0.0.1:0' as a
value for LISTEN env variable that is used in a lua test script. In
this way, the iproto port will be picked automatically, but if the test
needs the real value of the port, it has to execute `box.info.listen`
for …
> Free port auto resolving for TarantoolServer and AppServer

- lib/app_server.py
- lib/luatest_server.py
- lib/tarantool_server.py
- lib/unittest_server.py
Determination of debug build uses an incorrect regular expression: since it uses `re.I` flag (case insensitivity), it can match compiler flags contained in the version string, e.g. '--Wa,--debug-prefix-map==' — remove this flag and make the regular expression more specific.
Closes #352
> Fix determination of debug build

- lib/app_server.py
- lib/luatest_server.py
- lib/tarantool_server.py
- lib/unittest_server.py
The `tarantool -v` output is a single multiline string. Flag re.MULTILINE is required to match it with start of line (`^`) or end of line (`$`) characters. The `.*` in the middle of the pattern does not match start/end of lines, so this expression can not match something like this:
```
Target: Darwin-x86_64-Release
Build options: ... -Debug ...
```
The re.IGNORECASE is not required, because the build mode is always spelled in one particular way: `-Debug`.
Follow-up to #352
Fixes #355
Co-authored-by: Serge Petrenko <sergepetrenko@tarantool.org>
> Fix detection of debug builds

- README.md
We have no 'sophia' engine, since it was renamed to 'vinyl'.
> Fix README: remove outdated engine mentions

- .github/workflows/test.yml
New version includes the following commits:
- Print Tarantool version used by luatest [1]
- Change `coverage_report` parameter type to boolean [2]
- Forbid negative values for -r,--repeat option [3]
- Add new module server_v2.lua [4]
- Add --repeat-group option [5]
- Slightly prettify docs in server_v2.lua for LDoc [6]
- Merge server_v2.lua into server.lua [7]
[1] https://github.com/tarantool/luatest/commit/7b4acaaff5d65cf56b63cb2bafb45a81cd67dcc5 
[2] https://github.com/tarantool/luatest/commit/9cd0bf75cf2c0f0e11c03bfc07676b5412bca112 
[3] https://github.com/tarantool/luatest/commit/8c1f45561da2c3ad1f4656bd1a4405d585d3b7c6 
[4] https://github.com/tarantool/luatest/commit/287fb815c49555abf074a72e45aef0840f93f69f
[5] https://github.com/tarantool/luatest/commit/f07ab530d9ff19a55b69316b577cb3 …
> Bump luatest to 0.5.7-17-g1387aa8

- test_run.lua
Sometimes we don't care about zero component of the vclock, for example we want to ignore it when waiting for replica sync, using vclock (don't care about local spaces).
> test_run.lua: add ignore_zero option to get_vclock

- lib/worker.py
- listeners.py
- test-run.py
* Consider a test as 'flaky' if it was restarted at least 1 time
and eventually passed. Print the number of flaked tests and the
corresponding info in statistics.
* Collect logs of such tests into the 'artifacts' directory, along
with logs of failed tests.
Example:
$ ./test-run.py --force replication-luatest/
Started ./test-run.py --force replication-luatest/
Running in parallel with 16 workers
... <other tests>
[016] replication-luatest/gh_6033_box_promote_demote>                 [ pass ]
[014] replication-luatest/gh_5418_qsync_with_anon_te>                 [ pass ]
[012] replication-luatest/quorum_misc_test.lua                        [ pass ]
[005] replication-luatest/linearizable_test.lua                       [ fail ]
... <traceback>
[005] Test …
> Introduce flaky tests statistics 

- lib/worker.py
#330 describes a problem with searching a Lua module in the consistent mode:
```
./test/test-run.py sql-tap/collation -j -1
```
However, the same tests is working in the parallel mode with one worker process:
```
./test/test-run.py sql-tap/collation -j 1
```
First of all, the `sql-tap/collation` argument actually matches two tests:
* `sql-tap/collation_unicode.test.lua`
* `sql-tap/collation.test.lua`
The latter is marked as fragile, while the former has no such mark. test-run places them in two different task groups, which are served by two different worker instances. However, the test suite object is shared between them.
A worker's vardir is calculated as `suite's vardir + worker_name` and it is set back to the suite's vardir. This code is written in assumption that a test suite contains …
> consistent mode: fix worker's vardir calculation

- lib/tarantool_server.py
- requirements-test.txt
Locally flake8 reports me a style problem that is not detected in CI. This is distracting. Let's update flake8 in CI and fix the style problem.
flake8==6.\* doesn't support Python 3.7, but we have it in CI. Left flake8==5.* for a while.
> lint: update flake8 to 5.*

- lib/app_server.py
- lib/luatest_server.py
- lib/server.py
- lib/test.py
The patchset attempts to eliminate unnecessary bufferization and stdout/stderr streams mixing. It should improve observability in case of a failure (#119) and stability for tests that intensively writes to stderr (#392).
* app+luatest: add `-e "io.stdout:setvbuf('no')"` to tarantool command-line arguments.
* app+luatest: don't collect stdout in the memory till process termination, but write it directly to the temporary result file.
* luatest: split stdout and stderr files to give the TAP13 parser more chances to understand the stdout correctly.
Fixes #119
Fixes #392
----
I test it on small examples like the following:
```lua
$ cat test/app-tap/foo.test.lua
#!/usr/bin/env tarantool
local tap = require('tap')
local test = tap.test('foo')
while true do
test:ok(true, 'foo foo foo') …
```
> app+luatest: eliminate stdout buffering and stream mixing problems

- lib/tarantool_server.py
Creating a lua diff test with a name containing a dot causes the name to be parsed incorrectly. Then an attempt is made to create an tarantool instance with an incorrect name, resulting in an error. This change fixes the bug.
Fixes #300
> Fix bug when lua script name truncated by dot

- lib/options.py
Added logic that abort test run and logs an error message if
condition is not met: no-output-timeout is at least 10 seconds
longer than test-timeout and test-timeout is at least 10 seconds
longer than server-start-timeout.
Closes #250
> Raise an error and log it if test timeouts are set incorrectly

- requirements.txt
For now PyYAML=5.4.1 cannot be installed in Python 3.10.12 environment due to recently released Cython 3.0.0 [1]. This causes builds to fail. Pinned the dependency version to 5.3.1 until the issue [2] is solved.
[1] https://github.com/cython/cython/releases/tag/3.0.0
[2] https://github.com/yaml/pyyaml/issues/724
> Pin PyYAML version to `5.3.1`

- lib/__init__.py
- lib/options.py
- lib/tarantool_server.py
- tarantoolctl
In the near future we plan to test Tarantool installed from a DEB/RPM package. Since 3.0.0-alpha1 release [^1] Tarantool packages don't have the tarantoolctl utility inside [^2][^3].
[^1]: https://github.com/tarantool/tarantool/releases/tag/3.0.0-alpha1
[^2]: https://github.com/tarantool/tarantool/pull/8771
[^3]: https://github.com/tarantool/tarantool/pull/8866
It is necessary to "save" the tarantoolctl utility in order to use it regardless of whether it is part of future Tarantool packages or not. This can be done by simply copying the file to the root of the project directory.
```
$ docker run -v /tarantool:/tarantool -it debian:11 /bin/bash
root@14acb818b457:/# apt-get update && apt-get install python3-pip -y
root@14acb818b457:/# python3 --version
Python 3.9.2 …
```
> Migrate tarantoolctl from the tarantool repository

- lib/admin_connection.py
- lib/tarantool_server.py
- lib/worker.py
- listeners.py
Before this change, test-run crashed if the default tarantool server
had crashed with a segmentation fault, and as a result, this caused an
unhandled error with the broken tarantool console handshake. So such a
situation wasn't properly processed by test-run and it failed with the
following traceback:
Traceback (most recent call last):
File "/tarantool/test-run/lib/worker.py", line 283, in __init__
self.inspector = suite.start_server(self.server)
File "/tarantool/test-run/lib/test_suite.py", line 244, in start_server
server.deploy(silent=False)
File "/tarantool/test-run/lib/tarantool_server.py", line 784, in deploy
self.start(silent=silent, **kwargs)
File "/tarantool/test-run/lib/tarantool_server.py", line 911, in start
self.wait_until_started(wait_load, deadline)
File …
> Fix test-run crash when default server is crashed

- lib/app_server.py
Running jobs in tarantool-ci fails at the `action/upload-artifact` runtime if there are broken tests. The reason for the problem is that the path of the test artifacts file contains the `:` character when test has been parametrized.
Its **non-supported** character in the upload action. The action doesn't allow the following characters in artifact path: ",:,<,>,|,*,?. [^1]
To fix the problem, the `:` character has been replaced with `.`.
[^1]: https://github.com/actions/toolkit/blob/master/packages/artifact/docs/additional-information.md#non-supported-characters
Fixes https://github.com/tarantool/tarantool-qa/issues/90
> Fix incorrect character in log file name

- lib/luatest_server.py
New version includes the following commits related to luatest functionality:
- Parse custom net box URI (Unix socket) correctly [1]
- Move creating required resources to start funcs [2]
- Group some if conditions from `Server:initialize` [3]
- Not delete server's workdir in Server:drop() [4]
[1] tarantool/luatest@869ba1c
[2] tarantool/luatest@7d1358c
[3] tarantool/luatest@a188577
[4] tarantool/luatest@18859f6
> Bump luatest to 0.5.7-48-g18859f6

- lib/tarantool_server.py
In some tests, instances have duplicate file descriptors on one socket, which leads to abnormal termination of the test.
This patch removes duplicates to work around this problem.
> get_iproto_port: remove duplicates

- .github/workflows/test.yml
- requirements.txt
- requirements: bump gevent to 22.10.2
- ci: add testing against Python 3.11
- ci: add testing against Python 3.12
- ci: add testing against Tarantool 2.11
> requirements: bump gevent to 22.10.2

- lib/tarantool_server.py
When a diff test starts a Tarantool server, test-run reads the server log file and tries to find the message indicating the server is ready. Sometimes the server log file may contain bytes that cannot be decoded by `utf-8` codec and test-run fails with an error like this:
[044] TarantoolInpector.handle() received the following error:
[044] Traceback (most recent call last):
[044]   File "/tarantool/test-run/lib/inspector.py", line 98, in handle
[044]     result = self.parser.parse_preprocessor(line)
[044]   File "/tarantool/test-run/lib/preprocessor.py", line 123, in parse_preprocessor
[044]     return self.server(stype, sname, options)
[044]   File "/tarantool/test-run/lib/preprocessor.py", line 351, in server
[044]     return getattr(self, attr)(ctype, sname, opts)
[044]   File …
> Fix decoding error when reading server log file

- lib/test.py
The error is the following.
```python
[050] unit/mp_tuple.test
[050] TAP13 parse failed (Missing plan in the TAP source).
[050]
[050] No result file (unit/mp_tuple.result) found.
[050] Run the test with --update-result option to write the new result file.
[050]
[050] Worker "050_unit" received the following error; stopping...
[050] Traceback (most recent call last):
[050]   File "/__w/tarantool/tarantool/test-run/lib/worker.py", line 347, in run_task
[050]     short_status, duration = self.suite.run_test(
[050]   File "/__w/tarantool/tarantool/test-run/lib/test_suite.py", line 277, in run_test
[050]     short_status = test.run(server)
[050]   File "/__w/tarantool/tarantool/test-run/lib/test.py", line 233, in run
[050]     is_tap, is_ok, is_skip = self.check_tap_output()
[050] ValueError: …
```
> tap13: fix worker fail on failed TAP13 parsing

- dispatcher.py
A task queue dispatcher puts all the tasks to the task queue at startup. Then workers are started and are taking the tasks from it.
If there are many tasks in a task group (which roughly corresponds to a test suite), we can reach the pipe buffer size on putting into the queue, because `multiprocessing.SimpleQueue` uses a pipe under the hood.
The solution is to use `multiprocessing.Queue`, which has an intermediate buffer before the underlying pipe and writes to the pipe in a background thread, without blocking a thread that calls `<queue>.put()`.
The `Queue` API is a superset of the `SimpleQueue` API, so we can just replace the implementation.
Let's also use `Queue` for the worker's output queue to be on the safe side and for consistency.
Fixes #287
> dispatcher: lift pipe buffer size restriction

- lib/colorer.py
- lib/test_suite.py
- lib/utils.py
- test-run.py
Now the test configuration name is not trimmed if the terminal width allows it.
The idea can be illustrated this way:
```
+----------------------------------------------------------------------+
| Wide terminal                                                        |
+----------------------------------------------------------------------+
| suite/mytest_test.lua my_configuration                  [ pass ]     |
+----------------------------------------------------------------------+
+-------------------------------------------------+
| Narrow terminal                                 |
+-------------------------------------------------+
| suite/mytest_test.lua my_configur> [ pass ]     |
+-------------------------------------------------+
```
I want to add support for ability to run test …
> Adjust test result report width to terminal size

- lib/utils.py
- test-run.py
We're going to enable new ARM64 runners in CI, where test-run is invoked in a Docker container. At the same time, the runner is an LXD container created by the service provider. In this circumstances, the Docker container sees all the 128 online CPUs, but the runner may have only some of them available (depending on the pricing plan).
Python 3.3+ has a function to determine available CPUs, so we can reduce the parallelism to this value. We fall back to the online CPUs count on Python < 3.3.
After this change, test-run follows a CPU affinity mask set by `taskset` (and, I guess, by `numactl`).
The change is similar to replacing `nproc --all` to `nproc`.
The change only affects the default behavior, which can be overwritten by passing the `--jobs` (or `-j`) CLI option or using the …
> Calculate parallel jobs based on available CPUs

- lib/luatest_server.py
Requires https://github.com/tarantool/luatest/pull/378.
Feels better with #432.
----
In order to use the feature, add the following comment to a beginning of the test file:
```lua
-- tags: parallel
```
> luatest: allow to run test cases in parallel

- lib/luatest_server.py
It is a regression from commit 3b0ccd0721e5 ("luatest: detox test searching code"), PR #433.
The ability to run a test several times, especially in parallel, is very useful to reproduce and debug an unstable behavior in the test.
Fixes #437
> luatest: fix ability to run a test several times

- listeners.py
Previous attempt to fix this in commit 72905405cebe ("tap13: fix parsing non-utf8 chars") didn't take into account the hung test reporter, which also reads the result file in order to report how many lines into the result the test hung. Fix this as well.
Closes #442
> Follow-up fix for parsing non-utf8 chars

- test_run.lua
When waiting for cluster vclock, local component must be ignored because it's independent on each replica, so the commit fixes corresponding helper.
> ignore local lsn in wait_cluster_vclock

- test-run.py
The commit 17242110
("Adjust test result report width to terminal size") introduced a typo `RARAMS`, the patch fixes that.
> Fix a typo

- lib/test.py
This patch is similar to commit 52d3e4f7c90f ("Follow-up fix for parsing non-utf8 chars"),
but fixes the `--verbose` output, e.g.:
```
$ ./test-run.py --verbose some_test
[...]
[001] Worker "001_xxx-luatest" received the following error; stopping...
[001] Traceback (most recent call last):
[001]   File "./tarantool/test-run/lib/worker.py", line 357, in run_task
[001]     short_status, duration = self.suite.run_test(
[001]                              ^^^^^^^^^^^^^^^^^^^^
[001]   File "./tarantool/test-run/lib/test_suite.py", line 271, in run_test
[001]     short_status = test.run(server)
[001]                    ^^^^^^^^^^^^^^^^
[001]   File "./tarantool/test-run/lib/test.py", line 232, in run
[001]     color_stdout(f.read(), schema='log')
[001]                  ^^^^^^^^
[001]   File …
```
> Follow-up fix for parsing non-utf8 chars (part 2)
